// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "effect",
  id: "better_shine",
  name: "Better Shine",
  version: "1.0.0.2",
  category:
    // "blend",
    // "distortion",
    // "normal-mapping",
    // "tiling",
    // "other",
    "color",
  author: "skymen",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "A better shine effect",
  supportedRenderers: ["webgl", "webgpu"],
  blendsBackground: false,
  usesDepth: false,
  crossSampling: false,
  preservesOpaqueness: true,
  animated: false,
  mustPredraw: false,
  extendBox: {
    horizontal: 0,
    vertical: 0,
  },
  isDeprecated: false,
  parameters: [
    /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "float",
      id: "angle",
      value: 0,
      uniform: "uAngle",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Angle",
      desc: "The angle of the shine in degrees",
    },
    {
      type: "percent",
      id: "intensity",
      value: 1,
      uniform: "uIntensity",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Intensity",
      desc: "The intensity of the shine",
    },
    {
      type: "color",
      id: "color",
      value: [1, 1, 1, 1],
      uniform: "uColor",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Color",
      desc: "The color of the shine",
    },
    {
      type: "percent",
      id: "size",
      value: 0.1,
      uniform: "uSize",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Size",
      desc: "The size of the shine",
    },
    {
      type: "percent",
      id: "progress",
      value: 0,
      uniform: "uProgress",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Progress",
      desc: "The progress of the shine",
    },
    {
      type: "percent",
      id: "hardness",
      value: 0.5,
      uniform: "uHardness",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Hardness",
      desc: "The hardness of the shine",
    },
  ],
};
